### ISSUE TITLE
Rename anyref

### ISSUE THREAD

**Issue by protheory8** [kubkon/wasmtime-zig#12]
`anyref` is no longer called so, it was changed to `externref` some time ago.

**Comment by Luukdegram** [comment]
I assume you're talking about the `valkind` enum tag. Those names are from the C headers where they're still called `anyref` and `funcref` so I kept to that naming convention until they're updated as well. Perhaps it's worth it to rename it prematurely and keep closer to the spec, but naming isn't too high on my to-do list right now. Feel free to submit a PR if this is important to you.

**Comment by protheory8** [comment]
I didn't realize that they were still called like that in the C API proposal, sorry for bothering.

**Comment by Luukdegram** [comment]
No worries! Something like this is easy to be missed so I appreciate the headsup :)
